// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sssjfejrbxhdhklciknp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNzc2pmZWpyYnhoZGhrbGNpa25wIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg0NTI4NzIsImV4cCI6MjA3NDAyODg3Mn0.E7qG_tG1FSWCpy9o-A4eaDxgSPGVs8VX4U-QP7CJIXY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});